/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "STM32G071xx.h"

void delay(void){
	for(uint32_t i = 0; i < 500000; i++);
}


int main(void)
{

	GPIO_Handle_t Led;

	Led.pGPIOx = GPIOA;
	Led.GPIOPinConfig.GPIO_PinNumber = GPIO_PIN_5;
	Led.GPIOPinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Led.GPIOPinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	Led.GPIOPinConfig.GPIO_PinOPType = GPIO_OUT_PP;


	GPIO_PCLKControl(GPIOA, ENABLE);
	GPIO_Init(&Led);

	while(1){
		GPIO_TglPin(GPIOA, GPIO_PIN_5);
		delay();
	};

}
